In [1]:
from typing import List, Dict, Any
import glob

import pandas as pd
from pandas import DataFrame

# Домашняя работа 3

Загрузите файлы в датафреймы Pandas и назовите их coderun и users. 

Далее создайте новый датафрейм df, который получается в результате:

- Объединения двух датафреймов по полям с пользователем
- Если для каких-то кодранов не найдена пара в таблице users, такие записи нужно все равно оставить в результирующей таблице
- Если есть совпадающие названия столбцов, то у них в результате должны быть суффиксы _run и _user

Далее выполните действия:

- Создайте новый датафрейм df2, который будет хранить информацию о том, сколько дней прошло между последним выполнением кода конкретного юзера и днем его регистрации. Столбец с разницей должен называться diff.
- Округлите diff до ближайшего меньшего числа, кратного 50. Результат должен остаться целым числом.
- Создайте датафрейм df3, в который запишите количество юзеров, сгруппированных по разнице дней.
- Результат отсортируйте по убыванию количества user_id.

In [2]:
# Читаем файлы

coderun: DataFrame = pd.read_csv(
    "data/data/itresume-coderun.csv",
    delimiter=",",
    header=0
)

users: DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv",
    delimiter=";",
    header=1
)

In [3]:
# Смотрим, что там есть
coderun.head()

   id               created_at  problem_id  user_id  language_id
0   1  2021-04-07 06:06:20.000          13       10            3
1   2  2021-03-31 07:10:06.000          15       13            3
2   3  2021-04-04 14:55:26.000           1        6            3
3   4  2021-03-29 21:24:51.000          26        4            3
4   5  2021-03-30 11:29:12.000          21       18            3

In [4]:
# На всякий случай, посмотрим, порядок следования айдишников пользователей
coderun.sort_values(by="user_id", ascending=True)

          id               created_at  problem_id  user_id  language_id
22        23  2021-04-18 01:44:20.000           6        1            3
8          9  2021-04-06 12:14:59.000          24        1            3
98        99  2021-06-23 20:40:42.137           9        2            3
90        91  2021-06-23 15:54:14.915          11        2            3
91        92  2021-06-23 20:22:22.325           9        2            3
...      ...                      ...         ...      ...          ...
48434  48435  2022-04-20 20:54:20.353         171     2814            3
48451  48452  2022-04-20 21:01:16.737         171     2814            3
48438  48439  2022-04-20 20:55:39.797         171     2814            3
48435  48436  2022-04-20 20:54:39.747         171     2814            3
48430  48431  2022-04-20 20:50:57.715         166     2815            3

[55722 rows x 5 columns]

In [5]:
# Смотрим, что там есть
users.head()

    id       username          date_joined
0  416  nsosabisfsobm  2022-01-02 12:22:43
1   43    NbabnnbTona  2021-07-01 09:11:42
2   50           jbdn  2021-08-04 09:01:56
3  249       Kbaoxsnb  2021-11-27 07:03:35
4   77   bxakbasmo$$$  2021-11-09 14:31:46

In [6]:
# На всякий случай, посмотрим, порядок следования айдишников пользователей
users.sort_values(by="id", ascending=True)

      id       username          date_joined
1     43    NbabnnbTona  2021-07-01 09:11:42
2     50           jbdn  2021-08-04 09:01:56
4     77   bxakbasmo$$$  2021-11-09 14:31:46
5     80       ffbcnbms  2021-11-09 16:22:16
6     81         bdcson  2021-11-10 14:19:29
..   ...            ...                  ...
97  1050     nsosabndsi  2022-02-01 21:02:59
98  1076    SbsdSaobdox  2022-02-02 19:31:21
99  1090           Addb  2022-02-03 13:14:15
7   2633           Eabx  2022-04-06 08:52:40
9   2777  Jonns21241412  2022-04-18 09:33:09

[100 rows x 3 columns]

In [7]:
# Мержим аналогично LEFT JOIN

df: DataFrame = coderun.merge(
    users, 
    left_on="user_id", 
    right_on="id", 
    how="left"
)
df.sort_values(by="user_id")

,id_x,created_at,problem_id,user_id,language_id,id_y,username,date_joined
22,23,2021-04-18 01:44:20.000,6,1,3,NaN,NaN,NaN
8,9,2021-04-06 12:14:59.000,24,1,3,NaN,NaN,NaN
98,99,2021-06-23 20:40:42.137,9,2,3,NaN,NaN,NaN
90,91,2021-06-23 15:54:14.915,11,2,3,NaN,NaN,NaN
91,92,2021-06-23 20:22:22.325,9,2,3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
48434,48435,2022-04-20 20:54:20.353,171,2814,3,NaN,NaN,NaN
48451,48452,2022-04-20 21:01:16.737,171,2814,3,NaN,NaN,NaN
48438,48439,2022-04-20 20:55:39.797,171,2814,3,NaN,NaN,NaN
48435,48436,2022-04-20 20:54:39.747,171,2814,3,NaN,NaN,NaN
48430,48431,2022-04-20 20:50:57.715,166,2815,3,NaN,NaN,NaN

In [8]:
df.rename(columns={
    "id_x": "id_run",
    "id_y": "id_user"
})

,id_run,created_at,problem_id,user_id,language_id,id_user,username,date_joined
0,1,2021-04-07 06:06:20.000,13,10,3,NaN,NaN,NaN
1,2,2021-03-31 07:10:06.000,15,13,3,NaN,NaN,NaN
2,3,2021-04-04 14:55:26.000,1,6,3,NaN,NaN,NaN
3,4,2021-03-29 21:24:51.000,26,4,3,NaN,NaN,NaN
4,5,2021-03-30 11:29:12.000,21,18,3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
55717,55718,2022-05-17 09:00:51.743,101,171,2,NaN,NaN,NaN
55718,55719,2022-05-17 09:01:04.210,101,171,2,NaN,NaN,NaN
55719,55720,2022-05-17 09:02:06.203,101,171,2,NaN,NaN,NaN
55720,55721,2022-05-17 09:03:45.265,102,171,2,NaN,NaN,NaN
55721,55722,2022-05-17 09:03:57.645,102,171,2,NaN,NaN,NaN

In [11]:
# сколько дней прошло между последним выполнением кода конкретного юзера и днем его регистрации. Столбец с разницей должен называться diff.

processed: DataFrame = df.groupby(["user_id"]).count()
processed

,id_x,created_at,problem_id,language_id,id_y,username,date_joined
user_id,,,,,,,
1,2,2,2,2,0,0,0
2,265,265,265,265,0,0,0
3,3,3,3,3,0,0,0
4,1,1,1,1,0,0,0
5,1,1,1,1,0,0,0
...,...,...,...,...,...,...,...
2804,11,11,11,11,0,0,0
2812,69,69,69,69,0,0,0
2813,10,10,10,10,0,0,0
2814,37,37,37,37,0,0,0
2815,1,1,1,1,0,0,0